Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -33,29 +33,38 @@ jobs:
         uses: actions/checkout@v3
         with:
           path: sql-aide/support/docs-nextra 
-      - name: Detect package manager
-        id: detect-package-manager
-        run: |
-         cd sql-aide/support/docs-nextra
-          if [ -f "yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "package.json" ]; then
-            echo "manager=pnpm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+#       - name: Detect package manager
+#         id: detect-package-manager
+#         run: |
+#          cd sql-aide/support/docs-nextra
+#           if [ -f "yarn.lock" ]; then
+#             echo "manager=yarn" >> $GITHUB_OUTPUT
+#             echo "command=install" >> $GITHUB_OUTPUT
+#             echo "runner=yarn" >> $GITHUB_OUTPUT
+#             exit 0
+#           elif [ -f "package.json" ]; then
+#             echo "manager=pnpm" >> $GITHUB_OUTPUT
+#             echo "command=ci" >> $GITHUB_OUTPUT
+#             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+#             exit 0
+#           else
+#             echo "Unable to determine package manager"
+#             exit 1
+#           fi
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
           node-version: "16"
           cache: ${{ steps.detect-package-manager.outputs.manager }}
+          
+      - name: Install PNPM
+        run: npm install -g pnpm
+
+      - name: Install dependencies
+        run: |
+          cd sql-aide/support/docs-nextra
+          pnpm install
+        
       - name: Setup Pages
         uses: actions/configure-pages@v3
         with:
